#!/bin/sh
echo "🚀 Downloading..."
rm -rf yearglass
git clone https://github.com/ApolloZhu/yearglass.git
if [[ $? != 0 ]]; then
    echo "❌ Failed to download"
    exit 1
fi
cd yearglass

echo "🛠  Building..."
swift package clean
if [[ $? != 0 ]]; then
    echo "❌ Failed to clean"
    exit 1
fi
swift build -c release
if [[ $? != 0 ]]; then
    echo "❌ Failed to build"
    exit 1
fi

echo "💼  Installing..."
cp .build/release/yearglass-cli /usr/local/bin/yearglass
if [[ $? != 0 ]]; then
    cp .build/release/yearglass-cli ../yearglass
    MODE="LIMITED"
fi
cd ..
rm -rf yearglass

if [[ $MODE == "LIMITED" ]]; then
    export PATH=$PWD:"${PATH}"
    echo "⚠️  Adding $PWD to your \$PATH is recommended"
    chmod +x yearglass
fi
yearglass
if [[ $? != 0 ]]; then
    echo "❌ Failed to execute"
    exit 1
fi
